### PR TITLE
Add write_empty_files option

### PR DESCRIPTION
**Pull request by jordan-brough**
To allow dumping only the files that have data in them.

### CODE REVIEW

**Comment by amilligan** [comment]
Out of curiosity, what's your reason for this change?  The problem I see with not dumping empty files is that the fixture mechanism won't overwrite tables without corresponding fixture files.

On one hand, I imagine you may want this so you can have a table pre-populated with data that doesn't come from fixtures; that might make sense for a table of constant records that you don't want to reproduce in fixtures.

On the other hand, this opens a pretty big hole in the fixture mechanism, which is built on the foundation of data consistency.  The possibility that this hole could lead to test pollution or inconsistent tests on any project of non-trivial complexity seems to me like a fairly compelling reason to not make this change.

I'm curious to hear about the scenarios in which you use this change.

**Comment by rdy** [comment]
I agree with @amilligan on this, the empty files would force the fixtures to be cleared in test which is typically what you would want. That was the original design intention.

**Comment by jordan-brough** [comment]
> The problem I see with not dumping empty files is that the fixture mechanism won't overwrite tables without corresponding fixture files.

See the line immediately preceding this one.  fixture_builder already clears out all the existing fixture files before building new ones.

I have a lot of tables in my app but only a few that I put fixture data in.  Sometimes I manually look for things in the files and it's nice to not have a ton of empty files to have to skip around.

**Comment by jordan-brough** [comment]
@rdy any thoughts?

**Comment by rdy** [comment]
@jordan-brough alright this seems fine with me since it doesn't appear to change the default.

**Pull request merged**
