### PR TITLE
ActiveRecord 4.2 Deprecation Warning Fixes

### PR DESCRIPTION
**Pull request by brettg**
See https://github.com/rails/rails/pull/15704 and https://github.com/rails/rails/commit/d871807a78ca607f5f78e8eaab99e3d46f284c63

### CODE REVIEW

**Comment by brettg** [comment]
Should fix #30 and #28

**Comment by jhass** [comment]
@rdy Any chance you could take a look at this and maybe make a release?

**Comment by rdy** [comment]
yes, I'm planning to do a release soon, I wanted to fix the travis issue before doing so.

**Comment by jhass** [comment]
Try the new [container based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/), much better connectivity in my experience.

**Comment by dontfidget** [comment]
Hope this didn't get lost in the job change.  ;)  Would love to see this pulled.

**Comment by jhass** [comment]
@rdy ping.

**Comment by jhass** [comment]
@rdy we get a real lot deprecation warnings from this and they start to bury other stuff, so I'll just keep pinging you about this ;)

**Comment by rpbaltazar** [comment]
@rdy can we get this merged, please? Its really annoying to see 500 lines with the same deprecation message.

**Comment by SuperTux88** [comment]
@rdy can you please release this fix?

This could be temporarily fixed by adding https://gist.github.com/SuperTux88/59afc81f708f1f8039ce to config/initializers/fix-deprecation-warning.rb. This hides the deprecation warnings...

**Comment by SuperTux88** [comment]
Thanks :heart:

**Comment by rpbaltazar** [comment]
:clap: :+1:

**Pull request merged**
